apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "generic-azdo-deploy-chart.fullname" . }}
  labels:
    {{- include "generic-azdo-deploy-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
