apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-azdo-deploy-chart.fullname" . }}
  labels:
    {{- include "generic-azdo-deploy-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "generic-azdo-deploy-chart.selectorLabels" . | nindent 6 }}
