replicaCount: 3
environment: development
ingress:
  enabled: false
  host: unset
  path: unset
image:
  repository: generic-azdo-image-repository
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
containerPort: 8080
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
healthProbes:
  enabled: true
  startupProbe: 
    enabled: true
    path: /startup
    port: 8080
    periodSeconds: 10
    failureThreshold: 30
  livenessProbe: 
    enabled: true
    path: /health
    port: 8080
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe: 
    enabled: true
    path: /ready
    port: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
  requests:
    memory: "64Mi"
    cpu: "50m"
appName: generic-azdo
